pipeline {
    agent any
    
    parameters {
    	choice(name: 'TestChoice', choices: ['One', 'Two', 'Three'], description: 'Pick something')
    	
        string(name: 'TestHeading', defaultValue: 'None passed', description: 'Heading to be passed to the file')

        text(name: 'TestDescription', defaultValue: '', description: 'Enter some information about the person')

        password(name: 'TestPassword', defaultValue: 'SECRET', description: 'Enter a password')
    }

    stages {
    	stage('Clean Up') {
            steps {
                deleteDir()
            }
        }
        stage('Build') {
            steps {
                echo 'Building..'
                
                def data = "${params.TestChoice}\nHeading entered: ${params.TestHeading}\nDescription entered: ${params.TestDescription}\nPassword entered: ${params.TestPassword}"
                writeFile(file: 'output/file_from_pipeline.txt', text: data)
                
                writeFile file: ''
                sleep 5
            }
        }
        stage('Test') {
            steps {
                echo "Choice selected: ${params.TestChoice}"

                echo "Heading entered: ${params.TestHeading}"

                echo "Description entered: ${params.TestDescription}"

                echo "Password entered: ${params.TestPassword}"
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
                sleep 2
            }
        }
    }
}
